package io.agora.cruise.presto;

import io.agora.cruise.core.NodeRel;
import io.agora.cruise.core.ResultNode;
import io.agora.cruise.parser.SqlNodeTool;
import io.agora.cruise.parser.sql.presto.Int2BooleanConditionShuttle;
import io.agora.cruise.presto.simplify.PartitionAggregateFilterSimplify;
import org.apache.calcite.rel.RelNode;
import org.apache.calcite.sql.SqlNode;
import org.apache.calcite.sql.parser.SqlParseException;

import java.util.Collections;

import static io.agora.cruise.core.NodeUtils.createNodeRelRoot;
import static io.agora.cruise.core.NodeUtils.findFirstSubNode;

/** MergeResultTest. */
public class MergeResultTest {

    public static void main(String[] args) throws SqlParseException {
        PrestoContext context = new PrestoContext();
        final SqlNode sqlNode1 = SqlNodeTool.toQuerySqlNode("", new Int2BooleanConditionShuttle());

        final RelNode relNode1 = context.sqlNode2RelNode(sqlNode1);

        NodeRel.Simplify simplify =
                new PartitionAggregateFilterSimplify(Collections.singletonList("date"));

        NodeRel nodeRel1 = createNodeRelRoot(relNode1, simplify);
        System.out.println(context.toSql(nodeRel1.getPayload()));
    }

    private static void test1() throws SqlParseException {
        PrestoContext context = new PrestoContext();
        final SqlNode sqlNode1 =
                SqlNodeTool.toQuerySqlNode(sql1, new Int2BooleanConditionShuttle());
        final SqlNode sqlNode2 =
                SqlNodeTool.toQuerySqlNode(sql2, new Int2BooleanConditionShuttle());

        final RelNode relNode2 = context.sqlNode2RelNode(sqlNode2);
        final RelNode relNode1 = context.sqlNode2RelNode(sqlNode1);

        NodeRel.Simplify simplify =
                new PartitionAggregateFilterSimplify(Collections.singletonList("date"));

        NodeRel nodeRel1 = createNodeRelRoot(relNode1, simplify);
        NodeRel nodeRel2 = createNodeRelRoot(relNode2, simplify);
        ResultNode<RelNode> resultNode = findFirstSubNode(nodeRel1, nodeRel2);
        System.out.println(context.toSql(resultNode.getPayload()));
    }

    private static String sql1 =
            "SELECT SUM(\"自定义 SQL 查询\".\"s2l_25ms_delay_sec\") AS \"TEMP(Calculation_1430244791154503680)(2227145667)(0)\",\n"
                    + "  SUM(\"自定义 SQL 查询\".\"s2l_total_delay_sec\") AS \"TEMP(Calculation_1430244791154503680)(2460078802)(0)\",\n"
                    + "  SUM(\"自定义 SQL 查询\".\"5s_succ_join_ap_cnt\") AS \"TEMP(Calculation_1430244791247978510)(1716451703)(0)\",\n"
                    + "  SUM(\"自定义 SQL 查询\".\"total_join_ap_cnt\") AS \"TEMP(Calculation_1430244791247978510)(2681092799)(0)\",\n"
                    + "  SUM(\"自定义 SQL 查询\".\"video_totaltime_200\") AS \"TEMP(Calculation_2810035073237950465)(2104207895)(0)\",\n"
                    + "  SUM(\"自定义 SQL 查询\".\"video_freeze_time_200\") AS \"TEMP(Calculation_2810035073237950465)(530162565)(0)\",\n"
                    + "  SUM(\"自定义 SQL 查询\".\"totalJoin\") AS \"TEMP(Calculation_374009936508170240)(2073556184)(0)\",\n"
                    + "  SUM(\"自定义 SQL 查询\".\"totalJoinSuccess\") AS \"TEMP(Calculation_374009936508170240)(2807417001)(0)\",\n"
                    + "  SUM(\"自定义 SQL 查询\".\"threeSecJoinSuccess\") AS \"TEMP(Calculation_374009936508321793)(3693645608)(0)\",\n"
                    + "  SUM(\"自定义 SQL 查询\".\"fiveSecJoinSuccess\") AS \"TEMP(Calculation_374009936508416002)(383616769)(0)\",\n"
                    + "  SUM(\"自定义 SQL 查询\".\"video_totaltime\") AS \"TEMP(Calculation_374009936515215363)(2797449586)(0)\",\n"
                    + "  SUM(\"自定义 SQL 查询\".\"video_freeze_time\") AS \"TEMP(Calculation_374009936515215363)(2940759860)(0)\",\n"
                    + "  SUM(\"自定义 SQL 查询\".\"audio_totaltime\") AS \"TEMP(Calculation_374009936517861380)(1652566750)(0)\",\n"
                    + "  SUM(\"自定义 SQL 查询\".\"audio_freeze_time\") AS \"TEMP(Calculation_374009936517861380)(2919389392)(0)\",\n"
                    + "  SUM(\"自定义 SQL 查询\".\"p2s_lost_Leq5\") AS \"TEMP(Calculation_374009936519704581)(1936123547)(0)\",\n"
                    + "  SUM(\"自定义 SQL 查询\".\"p2s_lost_all\") AS \"TEMP(Calculation_374009936519704581)(749826584)(0)\",\n"
                    + "  SUM(\"自定义 SQL 查询\".\"s2l_75ms_delay_sec\") AS \"TEMP(Calculation_6542393318886285312)(2003933318)(0)\",\n"
                    + "  SUM(\"自定义 SQL 查询\".\"s2l_lost_Leq5\") AS \"TEMP(Calculation_7034341207026868236)(2745840127)(0)\",\n"
                    + "  SUM(\"自定义 SQL 查询\".\"s2l_lost_all\") AS \"TEMP(Calculation_7034341207026868236)(734589263)(0)\",\n"
                    + "  SUM(\"自定义 SQL 查询\".\"crash_cnt\") AS \"TEMP(Calculation_7034341207372070925)(2360900687)(0)\",\n"
                    + "  SUM(\"自定义 SQL 查询\".\"service_cnt\") AS \"TEMP(Calculation_7034341207372070925)(4291252132)(0)\",\n"
                    + "  DATE_ADD('SECOND', 0, date_parse(cast( \"自定义 SQL 查询\".\"date\" as VARCHAR), '%Y%m%d')) AS \"tdy_date_ok\"\n"
                    + "FROM (SELECT date,\n"
                    + "        CASE WHEN CAST(stat_period AS VARCHAR) = 'day' THEN substr(CAST(date_parse(cast( date as VARCHAR), '%Y%m%d') AS VARCHAR), 1, 10) ELSE concat(CAST(substr(CAST(start_date AS VARCHAR), 1, 10) AS VARCHAR), '~', CAST(substr(CAST(end_date AS VARCHAR), 1, 10) AS VARCHAR)) END AS period,\n"
                    + "      start_date,\n"
                    + "      end_date,\n"
                    + "      stat_period,\n"
                    + "      tag,\n"
                    + "      dim,\n"
                    + "      level1,\n"
                    + "      level2,\n"
                    + "      level3,\n"
                    + "      level4,\n"
                    + "      '' AS pd,\n"
                    + "      os,\n"
                    + "      ver,\n"
                    + "      ver_type,\n"
                    + "      '' AS product_line,\n"
                    + "      '' AS product_type,\n"
                    + "      domain,\n"
                    + "      country,\n"
                    + "      region,\n"
                    + "      net,\n"
                    + "      vid,\n"
                    + "      project,\n"
                    + "      company_id,\n"
                    + "      company_name,\n"
                    + "      rowsnum,\n"
                    + "      lastusage,\n"
                    + "      thisusage,\n"
                    + "      fiveSecJoinSuccess,\n"
                    + "      totalJoin,\n"
                    + "      cnt_sid,\n"
                    + "      video_freeze_time,\n"
                    + "      video_totaltime,\n"
                    + "      audio_freeze_time,\n"
                    + "      audio_totaltime,\n"
                    + "      s2l_total_delay_sec,\n"
                    + "      s2l_25ms_delay_sec,\n"
                    + "      s2l_75ms_delay_sec,\n"
                    + "      p2s_lost_Leq5,\n"
                    + "      p2s_lost_all,\n"
                    + "      crash_cnt,\n"
                    + "      service_cnt,\n"
                    + "      \"1s_succ_join_ap_cnt\",\n"
                    + "      \"5s_succ_join_ap_cnt\",\n"
                    + "      total_join_ap_cnt,\n"
                    + "      totalJoinSuccess,\n"
                    + "      threeSecJoinSuccess,\n"
                    + "      video_freeze_time_200,\n"
                    + "      video_totaltime_200,\n"
                    + "      video_freeze_time_500,\n"
                    + "      video_totaltime_500,\n"
                    + "      \"3s_succ_join_session_cnt_last1\",\n"
                    + "      \"5s_succ_join_session_cnt_last1\",\n"
                    + "      succ_join_session_cnt_last1,\n"
                    + "      total_join_session_cnt_last1,\n"
                    + "      total_session_cnt_last1,\n"
                    + "      \"1s_succ_join_ap_cnt_last1\",\n"
                    + "      \"5s_succ_join_ap_cnt_last1\",\n"
                    + "      total_join_ap_cnt_last1,\n"
                    + "      \"3s_succ_join_session_cnt_last7\",\n"
                    + "      \"5s_succ_join_session_cnt_last7\",\n"
                    + "      succ_join_session_cnt_last7,\n"
                    + "      total_join_session_cnt_last7,\n"
                    + "      total_session_cnt_last7,\n"
                    + "      \"1s_succ_join_ap_cnt_last7\",\n"
                    + "      \"5s_succ_join_ap_cnt_last7\",\n"
                    + "      total_join_ap_cnt_last7,\n"
                    + "      video_freeze_time_last1,\n"
                    + "      video_totaltime_last1,\n"
                    + "      video_freeze_time_500_last1,\n"
                    + "      video_totaltime_500_last1,\n"
                    + "      video_freeze_time_200_last1,\n"
                    + "      video_totaltime_200_last1,\n"
                    + "      video_freeze_time_last7,\n"
                    + "      video_totaltime_last7,\n"
                    + "      video_freeze_time_500_last7,\n"
                    + "      video_totaltime_500_last7,\n"
                    + "      video_freeze_time_200_last7,\n"
                    + "      video_totaltime_200_last7,\n"
                    + "      audio_freeze_time_last1,\n"
                    + "      audio_totaltime_last1,\n"
                    + "      audio_freeze_time_last7,\n"
                    + "      audio_totaltime_last7,\n"
                    + "      s2l_total_delay_sec_last1,\n"
                    + "      s2l_25ms_delay_sec_last1,\n"
                    + "      s2l_75ms_delay_sec_last1,\n"
                    + "      s2l_total_delay_sec_last7,\n"
                    + "      s2l_25ms_delay_sec_last7,\n"
                    + "      s2l_75ms_delay_sec_last7,\n"
                    + "      p2s_lost_Leq5_last1,\n"
                    + "      p2s_lost_all_last1,\n"
                    + "      p2s_lost_Leq5_last7,\n"
                    + "      p2s_lost_all_last7,\n"
                    + "      crash_cnt_last1,\n"
                    + "      service_cnt_last1,\n"
                    + "      crash_cnt_last7,\n"
                    + "      service_cnt_last7,\n"
                    + "      product_level1,\n"
                    + "      product_level2,\n"
                    + "      product_level3,\n"
                    + "      product_level4,\n"
                    + "      s2l_lost_Leq5,\n"
                    + "      s2l_lost_all,\n"
                    + "      s2l_lost_Leq5_last1,\n"
                    + "      s2l_lost_all_last1,\n"
                    + "      s2l_lost_Leq5_last7,\n"
                    + "      s2l_lost_all_last7\n"
                    + "    FROM report_datahub.pub_levels_quality_di_1\n"
                    + "    WHERE date_parse(cast( date as VARCHAR), '%Y%m%d') >= DATE('2021-11-21') AND date_parse(cast( date as VARCHAR), '%Y%m%d') <= DATE('2021-12-05')) AS \"自定义 SQL 查询\"\n"
                    + "WHERE CASE WHEN CAST(\"自定义 SQL 查询\".\"tag\" AS VARCHAR) = 'Industry' AND CAST(\"自定义 SQL 查询\".\"product_level1\" AS VARCHAR) = 'RTC' AND CAST(\"自定义 SQL 查询\".\"dim\" AS VARCHAR) = 'osver' THEN 0 WHEN CAST(\"自定义 SQL 查询\".\"tag\" AS VARCHAR) = 'VerType' AND CAST(\"自定义 SQL 查询\".\"product_level1\" AS VARCHAR) = 'RTC' AND CAST(\"自定义 SQL 查询\".\"dim\" AS VARCHAR) = 'osver' THEN 0 WHEN CAST(\"自定义 SQL 查询\".\"tag\" AS VARCHAR) = 'Product' AND CAST(\"自定义 SQL 查询\".\"product_level1\" AS VARCHAR) = 'RTC' AND CAST(\"自定义 SQL 查询\".\"dim\" AS VARCHAR) = 'osver' THEN 1 ELSE 0 END\n"
                    + "GROUP BY 22";

    private static final String sql2 =
            "SELECT SUM(\"自定义 SQL 查询\".\"s2l_25ms_delay_sec\") AS \"TEMP(Calculation_1430244791154503680)(2227145667)(0)\",\n"
                    + "  SUM(\"自定义 SQL 查询\".\"s2l_total_delay_sec\") AS \"TEMP(Calculation_1430244791154503680)(2460078802)(0)\",\n"
                    + "  SUM(\"自定义 SQL 查询\".\"5s_succ_join_ap_cnt\") AS \"TEMP(Calculation_1430244791247978510)(1716451703)(0)\",\n"
                    + "  SUM(\"自定义 SQL 查询\".\"total_join_ap_cnt\") AS \"TEMP(Calculation_1430244791247978510)(2681092799)(0)\",\n"
                    + "  SUM(\"自定义 SQL 查询\".\"video_totaltime_200\") AS \"TEMP(Calculation_2810035073237950465)(2104207895)(0)\",\n"
                    + "  SUM(\"自定义 SQL 查询\".\"video_freeze_time_200\") AS \"TEMP(Calculation_2810035073237950465)(530162565)(0)\",\n"
                    + "  SUM(\"自定义 SQL 查询\".\"totalJoin\") AS \"TEMP(Calculation_374009936508170240)(2073556184)(0)\",\n"
                    + "  SUM(\"自定义 SQL 查询\".\"totalJoinSuccess\") AS \"TEMP(Calculation_374009936508170240)(2807417001)(0)\",\n"
                    + "  SUM(\"自定义 SQL 查询\".\"threeSecJoinSuccess\") AS \"TEMP(Calculation_374009936508321793)(3693645608)(0)\",\n"
                    + "  SUM(\"自定义 SQL 查询\".\"fiveSecJoinSuccess\") AS \"TEMP(Calculation_374009936508416002)(383616769)(0)\",\n"
                    + "  SUM(\"自定义 SQL 查询\".\"video_totaltime\") AS \"TEMP(Calculation_374009936515215363)(2797449586)(0)\",\n"
                    + "  SUM(\"自定义 SQL 查询\".\"video_freeze_time\") AS \"TEMP(Calculation_374009936515215363)(2940759860)(0)\",\n"
                    + "  SUM(\"自定义 SQL 查询\".\"audio_totaltime\") AS \"TEMP(Calculation_374009936517861380)(1652566750)(0)\",\n"
                    + "  SUM(\"自定义 SQL 查询\".\"audio_freeze_time\") AS \"TEMP(Calculation_374009936517861380)(2919389392)(0)\",\n"
                    + "  SUM(\"自定义 SQL 查询\".\"p2s_lost_Leq5\") AS \"TEMP(Calculation_374009936519704581)(1936123547)(0)\",\n"
                    + "  SUM(\"自定义 SQL 查询\".\"p2s_lost_all\") AS \"TEMP(Calculation_374009936519704581)(749826584)(0)\",\n"
                    + "  SUM(\"自定义 SQL 查询\".\"s2l_75ms_delay_sec\") AS \"TEMP(Calculation_6542393318886285312)(2003933318)(0)\",\n"
                    + "  SUM(\"自定义 SQL 查询\".\"s2l_lost_Leq5\") AS \"TEMP(Calculation_7034341207026868236)(2745840127)(0)\",\n"
                    + "  SUM(\"自定义 SQL 查询\".\"s2l_lost_all\") AS \"TEMP(Calculation_7034341207026868236)(734589263)(0)\",\n"
                    + "  SUM(\"自定义 SQL 查询\".\"crash_cnt\") AS \"TEMP(Calculation_7034341207372070925)(2360900687)(0)\",\n"
                    + "  SUM(\"自定义 SQL 查询\".\"service_cnt\") AS \"TEMP(Calculation_7034341207372070925)(4291252132)(0)\",\n"
                    + "  DATE_ADD('SECOND', 0, date_parse(cast( \"自定义 SQL 查询\".\"date\" as VARCHAR), '%Y%m%d')) AS \"tdy_date_ok\"\n"
                    + "FROM (SELECT date,\n"
                    + "        CASE WHEN CAST(stat_period AS VARCHAR) = 'day' THEN substr(CAST(date_parse(cast( date as VARCHAR), '%Y%m%d') AS VARCHAR), 1, 10) ELSE concat(CAST(substr(CAST(start_date AS VARCHAR), 1, 10) AS VARCHAR), '~', CAST(substr(CAST(end_date AS VARCHAR), 1, 10) AS VARCHAR)) END AS period,\n"
                    + "      start_date,\n"
                    + "      end_date,\n"
                    + "      stat_period,\n"
                    + "      tag,\n"
                    + "      dim,\n"
                    + "      level1,\n"
                    + "      level2,\n"
                    + "      level3,\n"
                    + "      level4,\n"
                    + "      '' AS pd,\n"
                    + "      os,\n"
                    + "      ver,\n"
                    + "      ver_type,\n"
                    + "      '' AS product_line,\n"
                    + "      '' AS product_type,\n"
                    + "      domain,\n"
                    + "      country,\n"
                    + "      region,\n"
                    + "      net,\n"
                    + "      vid,\n"
                    + "      project,\n"
                    + "      company_id,\n"
                    + "      company_name,\n"
                    + "      rowsnum,\n"
                    + "      lastusage,\n"
                    + "      thisusage,\n"
                    + "      fiveSecJoinSuccess,\n"
                    + "      totalJoin,\n"
                    + "      cnt_sid,\n"
                    + "      video_freeze_time,\n"
                    + "      video_totaltime,\n"
                    + "      audio_freeze_time,\n"
                    + "      audio_totaltime,\n"
                    + "      s2l_total_delay_sec,\n"
                    + "      s2l_25ms_delay_sec,\n"
                    + "      s2l_75ms_delay_sec,\n"
                    + "      p2s_lost_Leq5,\n"
                    + "      p2s_lost_all,\n"
                    + "      crash_cnt,\n"
                    + "      service_cnt,\n"
                    + "      \"1s_succ_join_ap_cnt\",\n"
                    + "      \"5s_succ_join_ap_cnt\",\n"
                    + "      total_join_ap_cnt,\n"
                    + "      totalJoinSuccess,\n"
                    + "      threeSecJoinSuccess,\n"
                    + "      video_freeze_time_200,\n"
                    + "      video_totaltime_200,\n"
                    + "      video_freeze_time_500,\n"
                    + "      video_totaltime_500,\n"
                    + "      \"3s_succ_join_session_cnt_last1\",\n"
                    + "      \"5s_succ_join_session_cnt_last1\",\n"
                    + "      succ_join_session_cnt_last1,\n"
                    + "      total_join_session_cnt_last1,\n"
                    + "      total_session_cnt_last1,\n"
                    + "      \"1s_succ_join_ap_cnt_last1\",\n"
                    + "      \"5s_succ_join_ap_cnt_last1\",\n"
                    + "      total_join_ap_cnt_last1,\n"
                    + "      \"3s_succ_join_session_cnt_last7\",\n"
                    + "      \"5s_succ_join_session_cnt_last7\",\n"
                    + "      succ_join_session_cnt_last7,\n"
                    + "      total_join_session_cnt_last7,\n"
                    + "      total_session_cnt_last7,\n"
                    + "      \"1s_succ_join_ap_cnt_last7\",\n"
                    + "      \"5s_succ_join_ap_cnt_last7\",\n"
                    + "      total_join_ap_cnt_last7,\n"
                    + "      video_freeze_time_last1,\n"
                    + "      video_totaltime_last1,\n"
                    + "      video_freeze_time_500_last1,\n"
                    + "      video_totaltime_500_last1,\n"
                    + "      video_freeze_time_200_last1,\n"
                    + "      video_totaltime_200_last1,\n"
                    + "      video_freeze_time_last7,\n"
                    + "      video_totaltime_last7,\n"
                    + "      video_freeze_time_500_last7,\n"
                    + "      video_totaltime_500_last7,\n"
                    + "      video_freeze_time_200_last7,\n"
                    + "      video_totaltime_200_last7,\n"
                    + "      audio_freeze_time_last1,\n"
                    + "      audio_totaltime_last1,\n"
                    + "      audio_freeze_time_last7,\n"
                    + "      audio_totaltime_last7,\n"
                    + "      s2l_total_delay_sec_last1,\n"
                    + "      s2l_25ms_delay_sec_last1,\n"
                    + "      s2l_75ms_delay_sec_last1,\n"
                    + "      s2l_total_delay_sec_last7,\n"
                    + "      s2l_25ms_delay_sec_last7,\n"
                    + "      s2l_75ms_delay_sec_last7,\n"
                    + "      p2s_lost_Leq5_last1,\n"
                    + "      p2s_lost_all_last1,\n"
                    + "      p2s_lost_Leq5_last7,\n"
                    + "      p2s_lost_all_last7,\n"
                    + "      crash_cnt_last1,\n"
                    + "      service_cnt_last1,\n"
                    + "      crash_cnt_last7,\n"
                    + "      service_cnt_last7,\n"
                    + "      product_level1,\n"
                    + "      product_level2,\n"
                    + "      product_level3,\n"
                    + "      product_level4,\n"
                    + "      s2l_lost_Leq5,\n"
                    + "      s2l_lost_all,\n"
                    + "      s2l_lost_Leq5_last1,\n"
                    + "      s2l_lost_all_last1,\n"
                    + "      s2l_lost_Leq5_last7,\n"
                    + "      s2l_lost_all_last7\n"
                    + "    FROM report_datahub.pub_levels_quality_di_1\n"
                    + "    WHERE date_parse(cast( date as VARCHAR), '%Y%m%d') >= DATE('2021-11-21') AND date_parse(cast( date as VARCHAR), '%Y%m%d') <= DATE('2021-11-21')) AS \"自定义 SQL 查询\"\n"
                    + "WHERE CASE WHEN CAST(\"自定义 SQL 查询\".\"tag\" AS VARCHAR) = 'Industry' AND CAST(\"自定义 SQL 查询\".\"product_level1\" AS VARCHAR) = 'RTC' AND CAST(\"自定义 SQL 查询\".\"dim\" AS VARCHAR) = 'osver' THEN 0 WHEN CAST(\"自定义 SQL 查询\".\"tag\" AS VARCHAR) = 'VerType' AND CAST(\"自定义 SQL 查询\".\"product_level1\" AS VARCHAR) = 'RTC' AND CAST(\"自定义 SQL 查询\".\"dim\" AS VARCHAR) = 'osver' THEN 0 WHEN CAST(\"自定义 SQL 查询\".\"tag\" AS VARCHAR) = 'Product' AND CAST(\"自定义 SQL 查询\".\"product_level1\" AS VARCHAR) = 'RTC' AND CAST(\"自定义 SQL 查询\".\"dim\" AS VARCHAR) = 'osver' THEN 1 ELSE 0 END\n"
                    + "GROUP BY 22";
}
