package io.agora.cruise.presto.test.simplify;

import io.agora.cruise.core.NodeRel;
import io.agora.cruise.parser.SqlNodeTool;
import io.agora.cruise.parser.sql.presto.Int2BooleanConditionShuttle;
import io.agora.cruise.presto.PrestoContext;
import io.agora.cruise.presto.simplify.PartitionAggregateFilterSimplify;
import org.apache.calcite.rel.RelNode;
import org.apache.calcite.sql.SqlNode;
import org.apache.calcite.sql.parser.SqlParseException;
import org.junit.Test;

import java.util.Collections;

import static io.agora.cruise.core.NodeUtils.createNodeRelRoot;

/** PartitionAggregateFilterSimplifyTest. */
public class PartitionAggregateFilterSimplifyTest {

    @Test
    public void test() throws SqlParseException {
        PrestoContext context = new PrestoContext();
        final SqlNode sqlNode1 = SqlNodeTool.toQuerySqlNode(sql, new Int2BooleanConditionShuttle());

        final RelNode relNode1 = context.sqlNode2RelNode(sqlNode1);

        NodeRel.Simplify simplify =
                new PartitionAggregateFilterSimplify(Collections.singletonList("date"));

        NodeRel nodeRel1 = createNodeRelRoot(relNode1, simplify);
        System.out.println(context.toSql(nodeRel1.getPayload()));
    }

    private final String sql =
            "SELECT SUM(\"自定义 SQL 查询\".\"s2l_25ms_delay_sec\") AS \"TEMP(Calculation_1430244791154503680)(2227145667)(0)\",\n"
                    + "  SUM(\"自定义 SQL 查询\".\"s2l_total_delay_sec\") AS \"TEMP(Calculation_1430244791154503680)(2460078802)(0)\",\n"
                    + "  SUM(\"自定义 SQL 查询\".\"s2l_total_delay_sec_last1\") AS \"TEMP(Calculation_1430244791161831425)(1533897333)(0)\",\n"
                    + "  SUM(\"自定义 SQL 查询\".\"s2l_25ms_delay_sec_last1\") AS \"TEMP(Calculation_1430244791161831425)(3105382701)(0)\",\n"
                    + "  SUM(\"自定义 SQL 查询\".\"5s_succ_join_ap_cnt\") AS \"TEMP(Calculation_1430244791247978510)(1716451703)(0)\",\n"
                    + "  SUM(\"自定义 SQL 查询\".\"total_join_ap_cnt\") AS \"TEMP(Calculation_1430244791247978510)(2681092799)(0)\",\n"
                    + "  SUM(\"自定义 SQL 查询\".\"5s_succ_join_ap_cnt_last1\") AS \"TEMP(Calculation_1430244791248527375)(865560869)(0)\",\n"
                    + "  SUM(\"自定义 SQL 查询\".\"total_join_ap_cnt_last1\") AS \"TEMP(Calculation_1430244791248527375)(97423155)(0)\",\n"
                    + "  SUM(\"自定义 SQL 查询\".\"video_freeze_time_500\") AS \"TEMP(Calculation_1857594119395086336)(389023081)(0)\",\n"
                    + "  SUM(\"自定义 SQL 查询\".\"video_totaltime_500\") AS \"TEMP(Calculation_1857594119395086336)(458654145)(0)\",\n"
                    + "  SUM(\"自定义 SQL 查询\".\"video_totaltime_500_last1\") AS \"TEMP(Calculation_1857594119395348481)(3425883446)(0)\",\n"
                    + "  SUM(\"自定义 SQL 查询\".\"video_freeze_time_500_last1\") AS \"TEMP(Calculation_1857594119395348481)(3450234468)(0)\",\n"
                    + "  SUM(\"自定义 SQL 查询\".\"video_totaltime_200\") AS \"TEMP(Calculation_2033093767653158912)(2104207895)(0)\",\n"
                    + "  SUM(\"自定义 SQL 查询\".\"video_freeze_time_200\") AS \"TEMP(Calculation_2033093767653158912)(530162565)(0)\",\n"
                    + "  SUM(\"自定义 SQL 查询\".\"video_totaltime_200_last1\") AS \"TEMP(Calculation_2033093767653347329)(1909093697)(0)\",\n"
                    + "  SUM(\"自定义 SQL 查询\".\"video_freeze_time_200_last1\") AS \"TEMP(Calculation_2033093767653347329)(2193258393)(0)\",\n"
                    + "  SUM(\"自定义 SQL 查询\".\"totalJoin\") AS \"TEMP(Calculation_374009936508170240)(2073556184)(0)\",\n"
                    + "  SUM(\"自定义 SQL 查询\".\"totalJoinSuccess\") AS \"TEMP(Calculation_374009936508170240)(2807417001)(0)\",\n"
                    + "  SUM(\"自定义 SQL 查询\".\"threeSecJoinSuccess\") AS \"TEMP(Calculation_374009936508321793)(3693645608)(0)\",\n"
                    + "  SUM(\"自定义 SQL 查询\".\"fiveSecJoinSuccess\") AS \"TEMP(Calculation_374009936508416002)(383616769)(0)\",\n"
                    + "  SUM(\"自定义 SQL 查询\".\"video_totaltime\") AS \"TEMP(Calculation_374009936515215363)(2797449586)(0)\",\n"
                    + "  SUM(\"自定义 SQL 查询\".\"video_freeze_time\") AS \"TEMP(Calculation_374009936515215363)(2940759860)(0)\",\n"
                    + "  SUM(\"自定义 SQL 查询\".\"audio_totaltime\") AS \"TEMP(Calculation_374009936517861380)(1652566750)(0)\",\n"
                    + "  SUM(\"自定义 SQL 查询\".\"audio_freeze_time\") AS \"TEMP(Calculation_374009936517861380)(2919389392)(0)\",\n"
                    + "  SUM(\"自定义 SQL 查询\".\"p2s_lost_Leq5\") AS \"TEMP(Calculation_374009936519704581)(1936123547)(0)\",\n"
                    + "  SUM(\"自定义 SQL 查询\".\"p2s_lost_all\") AS \"TEMP(Calculation_374009936519704581)(749826584)(0)\",\n"
                    + "  SUM(\"自定义 SQL 查询\".\"total_join_session_cnt_last1\") AS \"TEMP(Calculation_374009936523853831)(2708102775)(0)\",\n"
                    + "  SUM(\"自定义 SQL 查询\".\"succ_join_session_cnt_last1\") AS \"TEMP(Calculation_374009936523853831)(929207889)(0)\",\n"
                    + "  SUM(\"自定义 SQL 查询\".\"s2l_75ms_delay_sec\") AS \"TEMP(Calculation_6542393318886285312)(2003933318)(0)\",\n"
                    + "  SUM(\"自定义 SQL 查询\".\"s2l_total_delay_sec_last1\") AS \"TEMP(Calculation_6542393318886735875)(3088956105)(0)\",\n"
                    + "  SUM(\"自定义 SQL 查询\".\"s2l_75ms_delay_sec_last1\") AS \"TEMP(Calculation_6542393318886735875)(602483182)(0)\",\n"
                    + "  SUM(\"自定义 SQL 查询\".\"s2l_lost_Leq5\") AS \"TEMP(Calculation_7012034266496475136)(2745840127)(0)\",\n"
                    + "  SUM(\"自定义 SQL 查询\".\"s2l_lost_all\") AS \"TEMP(Calculation_7012034266496475136)(734589263)(0)\",\n"
                    + "  SUM(\"自定义 SQL 查询\".\"s2l_lost_all_last1\") AS \"TEMP(Calculation_7012034266496618497)(3348338895)(0)\",\n"
                    + "  SUM(\"自定义 SQL 查询\".\"s2l_lost_Leq5_last1\") AS \"TEMP(Calculation_7012034266496618497)(700826822)(0)\",\n"
                    + "  SUM(\"自定义 SQL 查询\".\"3s_succ_join_session_cnt_last1\") AS \"TEMP(Calculation_7034341207020355584)(2445597373)(0)\",\n"
                    + "  SUM(\"自定义 SQL 查询\".\"5s_succ_join_session_cnt_last1\") AS \"TEMP(Calculation_7034341207023706114)(2534022291)(0)\",\n"
                    + "  SUM(\"自定义 SQL 查询\".\"video_totaltime_last1\") AS \"TEMP(Calculation_7034341207025315846)(1221500367)(0)\",\n"
                    + "  SUM(\"自定义 SQL 查询\".\"video_freeze_time_last1\") AS \"TEMP(Calculation_7034341207025315846)(3506758486)(0)\",\n"
                    + "  SUM(\"自定义 SQL 查询\".\"audio_totaltime_last1\") AS \"TEMP(Calculation_7034341207025774600)(803828507)(0)\",\n"
                    + "  SUM(\"自定义 SQL 查询\".\"audio_freeze_time_last1\") AS \"TEMP(Calculation_7034341207025774600)(877259553)(0)\",\n"
                    + "  SUM(\"自定义 SQL 查询\".\"crash_cnt\") AS \"TEMP(Calculation_7034341207372070925)(2360900687)(0)\",\n"
                    + "  SUM(\"自定义 SQL 查询\".\"service_cnt\") AS \"TEMP(Calculation_7034341207372070925)(4291252132)(0)\",\n"
                    + "  SUM(\"自定义 SQL 查询\".\"service_cnt_last1\") AS \"TEMP(Calculation_7034341207372197902)(2436060403)(0)\",\n"
                    + "  SUM(\"自定义 SQL 查询\".\"crash_cnt_last1\") AS \"TEMP(Calculation_7034341207372197902)(651130603)(0)\",\n"
                    + "  SUM(\"自定义 SQL 查询\".\"p2s_lost_all_last1\") AS \"TEMP(Calculation_75998310509129730)(1975694301)(0)\",\n"
                    + "  SUM(\"自定义 SQL 查询\".\"p2s_lost_Leq5_last1\") AS \"TEMP(Calculation_75998310509129730)(1982054307)(0)\"\n"
                    + "FROM (SELECT t1.date,\n"
                    + "        CASE WHEN CAST(stat_period AS VARCHAR) = 'day' THEN substr(CAST(date_parse(cast( t1.date as VARCHAR), '%Y%m%d') AS VARCHAR), 1, 10) ELSE concat(CAST(substr(CAST(start_date AS VARCHAR), 1, 10) AS VARCHAR), '~', CAST(substr(CAST(end_date AS VARCHAR), 1, 10) AS VARCHAR)) END AS period,\n"
                    + "      start_date,\n"
                    + "      end_date,\n"
                    + "      stat_period,\n"
                    + "      tag,\n"
                    + "      t1.dim,\n"
                    + "      level1,\n"
                    + "      level2,\n"
                    + "      level3,\n"
                    + "      level4,\n"
                    + "      os,\n"
                    + "      ver,\n"
                    + "      ver_type,\n"
                    + "      domain,\n"
                    + "      country,\n"
                    + "      region,\n"
                    + "      net,\n"
                    + "      vid,\n"
                    + "      project,\n"
                    + "      company_id,\n"
                    + "      company_name,\n"
                    + "      rowsnum,\n"
                    + "      lastusage,\n"
                    + "      thisusage,\n"
                    + "      fiveSecJoinSuccess,\n"
                    + "      totalJoin,\n"
                    + "      cnt_sid,\n"
                    + "      video_freeze_time,\n"
                    + "      video_totaltime,\n"
                    + "      audio_freeze_time,\n"
                    + "      audio_totaltime,\n"
                    + "      s2l_total_delay_sec,\n"
                    + "      s2l_25ms_delay_sec,\n"
                    + "      s2l_75ms_delay_sec,\n"
                    + "      p2s_lost_Leq5,\n"
                    + "      p2s_lost_all,\n"
                    + "      crash_cnt,\n"
                    + "      service_cnt,\n"
                    + "      \"1s_succ_join_ap_cnt\",\n"
                    + "      \"5s_succ_join_ap_cnt\",\n"
                    + "      total_join_ap_cnt,\n"
                    + "      totalJoinSuccess,\n"
                    + "      threeSecJoinSuccess,\n"
                    + "      video_freeze_time_200,\n"
                    + "      video_totaltime_200,\n"
                    + "      video_freeze_time_500,\n"
                    + "      video_totaltime_500,\n"
                    + "      \"3s_succ_join_session_cnt_last1\",\n"
                    + "      \"5s_succ_join_session_cnt_last1\",\n"
                    + "      succ_join_session_cnt_last1,\n"
                    + "      total_join_session_cnt_last1,\n"
                    + "      total_session_cnt_last1,\n"
                    + "      \"1s_succ_join_ap_cnt_last1\",\n"
                    + "      \"5s_succ_join_ap_cnt_last1\",\n"
                    + "      total_join_ap_cnt_last1,\n"
                    + "      \"3s_succ_join_session_cnt_last7\",\n"
                    + "      \"5s_succ_join_session_cnt_last7\",\n"
                    + "      succ_join_session_cnt_last7,\n"
                    + "      total_join_session_cnt_last7,\n"
                    + "      total_session_cnt_last7,\n"
                    + "      \"1s_succ_join_ap_cnt_last7\",\n"
                    + "      \"5s_succ_join_ap_cnt_last7\",\n"
                    + "      total_join_ap_cnt_last7,\n"
                    + "      video_freeze_time_last1,\n"
                    + "      video_totaltime_last1,\n"
                    + "      video_freeze_time_500_last1,\n"
                    + "      video_totaltime_500_last1,\n"
                    + "      video_freeze_time_200_last1,\n"
                    + "      video_totaltime_200_last1,\n"
                    + "      video_freeze_time_last7,\n"
                    + "      video_totaltime_last7,\n"
                    + "      video_freeze_time_500_last7,\n"
                    + "      video_totaltime_500_last7,\n"
                    + "      video_freeze_time_200_last7,\n"
                    + "      video_totaltime_200_last7,\n"
                    + "      audio_freeze_time_last1,\n"
                    + "      audio_totaltime_last1,\n"
                    + "      audio_freeze_time_last7,\n"
                    + "      audio_totaltime_last7,\n"
                    + "      s2l_total_delay_sec_last1,\n"
                    + "      s2l_25ms_delay_sec_last1,\n"
                    + "      s2l_75ms_delay_sec_last1,\n"
                    + "      s2l_total_delay_sec_last7,\n"
                    + "      s2l_25ms_delay_sec_last7,\n"
                    + "      s2l_75ms_delay_sec_last7,\n"
                    + "      p2s_lost_Leq5_last1,\n"
                    + "      p2s_lost_all_last1,\n"
                    + "      p2s_lost_Leq5_last7,\n"
                    + "      p2s_lost_all_last7,\n"
                    + "      crash_cnt_last1,\n"
                    + "      service_cnt_last1,\n"
                    + "      crash_cnt_last7,\n"
                    + "      service_cnt_last7,\n"
                    + "      product_level1,\n"
                    + "      product_level2,\n"
                    + "      product_level3,\n"
                    + "      product_level4,\n"
                    + "      s2l_lost_Leq5,\n"
                    + "      s2l_lost_all,\n"
                    + "      s2l_lost_Leq5_last1,\n"
                    + "      s2l_lost_all_last1,\n"
                    + "      s2l_lost_Leq5_last7,\n"
                    + "      s2l_lost_all_last7,\n"
                    + "      fiveSecJoinSuccess_total,\n"
                    + "      totalJoin_total,\n"
                    + "      cnt_sid_total,\n"
                    + "      video_freeze_time_total,\n"
                    + "      video_totaltime_total,\n"
                    + "      audio_freeze_time_total,\n"
                    + "      audio_totaltime_total,\n"
                    + "      s2l_total_delay_sec_total,\n"
                    + "      s2l_25ms_delay_sec_total,\n"
                    + "      s2l_75ms_delay_sec_total,\n"
                    + "      p2s_lost_Leq5_total,\n"
                    + "      p2s_lost_all_total,\n"
                    + "      crash_cnt_total,\n"
                    + "      service_cnt_total,\n"
                    + "      \"1s_succ_join_ap_cnt_total\",\n"
                    + "      \"5s_succ_join_ap_cnt_total\",\n"
                    + "      total_join_ap_cnt_total,\n"
                    + "      totalJoinSuccess_total,\n"
                    + "      threeSecJoinSuccess_total,\n"
                    + "      video_freeze_time_200_total,\n"
                    + "      video_totaltime_200_total,\n"
                    + "      video_freeze_time_500_total,\n"
                    + "      video_totaltime_500_total,\n"
                    + "      \"3s_succ_join_session_cnt_last1_total\",\n"
                    + "      \"5s_succ_join_session_cnt_last1_total\",\n"
                    + "      succ_join_session_cnt_last1_total,\n"
                    + "      total_join_session_cnt_last1_total,\n"
                    + "      total_session_cnt_last1_total,\n"
                    + "      \"1s_succ_join_ap_cnt_last1_total\",\n"
                    + "      \"5s_succ_join_ap_cnt_last1_total\",\n"
                    + "      total_join_ap_cnt_last1_total,\n"
                    + "      \"3s_succ_join_session_cnt_last7_total\",\n"
                    + "      \"5s_succ_join_session_cnt_last7_total\",\n"
                    + "      succ_join_session_cnt_last7_total,\n"
                    + "      total_join_session_cnt_last7_total,\n"
                    + "      total_session_cnt_last7_total,\n"
                    + "      \"1s_succ_join_ap_cnt_last7_total\",\n"
                    + "      \"5s_succ_join_ap_cnt_last7_total\",\n"
                    + "      total_join_ap_cnt_last7_total,\n"
                    + "      video_freeze_time_last1_total,\n"
                    + "      video_totaltime_last1_total,\n"
                    + "      video_freeze_time_500_last1_total,\n"
                    + "      video_totaltime_500_last1_total,\n"
                    + "      video_freeze_time_200_last1_total,\n"
                    + "      video_totaltime_200_last1_total,\n"
                    + "      video_freeze_time_last7_total,\n"
                    + "      video_totaltime_last7_total,\n"
                    + "      video_freeze_time_500_last7_total,\n"
                    + "      video_totaltime_500_last7_total,\n"
                    + "      video_freeze_time_200_last7_total,\n"
                    + "      video_totaltime_200_last7_total,\n"
                    + "      audio_freeze_time_last1_total,\n"
                    + "      audio_totaltime_last1_total,\n"
                    + "      audio_freeze_time_last7_total,\n"
                    + "      audio_totaltime_last7_total,\n"
                    + "      s2l_total_delay_sec_last1_total,\n"
                    + "      s2l_25ms_delay_sec_last1_total,\n"
                    + "      s2l_75ms_delay_sec_last1_total,\n"
                    + "      s2l_total_delay_sec_last7_total,\n"
                    + "      s2l_25ms_delay_sec_last7_total,\n"
                    + "      s2l_75ms_delay_sec_last7_total,\n"
                    + "      p2s_lost_Leq5_last1_total,\n"
                    + "      p2s_lost_all_last1_total,\n"
                    + "      p2s_lost_Leq5_last7_total,\n"
                    + "      p2s_lost_all_last7_total,\n"
                    + "      crash_cnt_last1_total,\n"
                    + "      service_cnt_last1_total,\n"
                    + "      crash_cnt_last7_total,\n"
                    + "      service_cnt_last7_total,\n"
                    + "      s2l_lost_Leq5_total,\n"
                    + "      s2l_lost_all_total,\n"
                    + "      s2l_lost_Leq5_last1_total,\n"
                    + "      s2l_lost_all_last1_total,\n"
                    + "      s2l_lost_Leq5_last7_total,\n"
                    + "      s2l_lost_all_last7_total\n"
                    + "    FROM report_datahub.pub_levels_quality_di_1 AS t1\n"
                    + "      LEFT JOIN (SELECT date,\n"
                    + "          dim,\n"
                    + "          SUM(fiveSecJoinSuccess) AS fiveSecJoinSuccess_total,\n"
                    + "          SUM(totalJoin) AS totalJoin_total,\n"
                    + "          SUM(cnt_sid) AS cnt_sid_total,\n"
                    + "          SUM(video_freeze_time) AS video_freeze_time_total,\n"
                    + "          SUM(video_totaltime) AS video_totaltime_total,\n"
                    + "          SUM(audio_freeze_time) AS audio_freeze_time_total,\n"
                    + "          SUM(audio_totaltime) AS audio_totaltime_total,\n"
                    + "          SUM(s2l_total_delay_sec) AS s2l_total_delay_sec_total,\n"
                    + "          SUM(s2l_25ms_delay_sec) AS s2l_25ms_delay_sec_total,\n"
                    + "          SUM(s2l_75ms_delay_sec) AS s2l_75ms_delay_sec_total,\n"
                    + "          SUM(p2s_lost_Leq5) AS p2s_lost_Leq5_total,\n"
                    + "          SUM(p2s_lost_all) AS p2s_lost_all_total,\n"
                    + "          SUM(crash_cnt) AS crash_cnt_total,\n"
                    + "          SUM(service_cnt) AS service_cnt_total,\n"
                    + "          SUM(\"1s_succ_join_ap_cnt\") AS \"1s_succ_join_ap_cnt_total\",\n"
                    + "          SUM(\"5s_succ_join_ap_cnt\") AS \"5s_succ_join_ap_cnt_total\",\n"
                    + "          SUM(total_join_ap_cnt) AS total_join_ap_cnt_total,\n"
                    + "          SUM(totalJoinSuccess) AS totalJoinSuccess_total,\n"
                    + "          SUM(threeSecJoinSuccess) AS threeSecJoinSuccess_total,\n"
                    + "          SUM(video_freeze_time_200) AS video_freeze_time_200_total,\n"
                    + "          SUM(video_totaltime_200) AS video_totaltime_200_total,\n"
                    + "          SUM(video_freeze_time_500) AS video_freeze_time_500_total,\n"
                    + "          SUM(video_totaltime_500) AS video_totaltime_500_total,\n"
                    + "          SUM(\"3s_succ_join_session_cnt_last1\") AS \"3s_succ_join_session_cnt_last1_total\",\n"
                    + "          SUM(\"5s_succ_join_session_cnt_last1\") AS \"5s_succ_join_session_cnt_last1_total\",\n"
                    + "          SUM(succ_join_session_cnt_last1) AS succ_join_session_cnt_last1_total,\n"
                    + "          SUM(total_join_session_cnt_last1) AS total_join_session_cnt_last1_total,\n"
                    + "          SUM(total_session_cnt_last1) AS total_session_cnt_last1_total,\n"
                    + "          SUM(\"1s_succ_join_ap_cnt_last1\") AS \"1s_succ_join_ap_cnt_last1_total\",\n"
                    + "          SUM(\"5s_succ_join_ap_cnt_last1\") AS \"5s_succ_join_ap_cnt_last1_total\",\n"
                    + "          SUM(total_join_ap_cnt_last1) AS total_join_ap_cnt_last1_total,\n"
                    + "          SUM(\"3s_succ_join_session_cnt_last7\") AS \"3s_succ_join_session_cnt_last7_total\",\n"
                    + "          SUM(\"5s_succ_join_session_cnt_last7\") AS \"5s_succ_join_session_cnt_last7_total\",\n"
                    + "          SUM(succ_join_session_cnt_last7) AS succ_join_session_cnt_last7_total,\n"
                    + "          SUM(total_join_session_cnt_last7) AS total_join_session_cnt_last7_total,\n"
                    + "          SUM(total_session_cnt_last7) AS total_session_cnt_last7_total,\n"
                    + "          SUM(\"1s_succ_join_ap_cnt_last7\") AS \"1s_succ_join_ap_cnt_last7_total\",\n"
                    + "          SUM(\"5s_succ_join_ap_cnt_last7\") AS \"5s_succ_join_ap_cnt_last7_total\",\n"
                    + "          SUM(total_join_ap_cnt_last7) AS total_join_ap_cnt_last7_total,\n"
                    + "          SUM(video_freeze_time_last1) AS video_freeze_time_last1_total,\n"
                    + "          SUM(video_totaltime_last1) AS video_totaltime_last1_total,\n"
                    + "          SUM(video_freeze_time_500_last1) AS video_freeze_time_500_last1_total,\n"
                    + "          SUM(video_totaltime_500_last1) AS video_totaltime_500_last1_total,\n"
                    + "          SUM(video_freeze_time_200_last1) AS video_freeze_time_200_last1_total,\n"
                    + "          SUM(video_totaltime_200_last1) AS video_totaltime_200_last1_total,\n"
                    + "          SUM(video_freeze_time_last7) AS video_freeze_time_last7_total,\n"
                    + "          SUM(video_totaltime_last7) AS video_totaltime_last7_total,\n"
                    + "          SUM(video_freeze_time_500_last7) AS video_freeze_time_500_last7_total,\n"
                    + "          SUM(video_totaltime_500_last7) AS video_totaltime_500_last7_total,\n"
                    + "          SUM(video_freeze_time_200_last7) AS video_freeze_time_200_last7_total,\n"
                    + "          SUM(video_totaltime_200_last7) AS video_totaltime_200_last7_total,\n"
                    + "          SUM(audio_freeze_time_last1) AS audio_freeze_time_last1_total,\n"
                    + "          SUM(audio_totaltime_last1) AS audio_totaltime_last1_total,\n"
                    + "          SUM(audio_freeze_time_last7) AS audio_freeze_time_last7_total,\n"
                    + "          SUM(audio_totaltime_last7) AS audio_totaltime_last7_total,\n"
                    + "          SUM(s2l_total_delay_sec_last1) AS s2l_total_delay_sec_last1_total,\n"
                    + "          SUM(s2l_25ms_delay_sec_last1) AS s2l_25ms_delay_sec_last1_total,\n"
                    + "          SUM(s2l_75ms_delay_sec_last1) AS s2l_75ms_delay_sec_last1_total,\n"
                    + "          SUM(s2l_total_delay_sec_last7) AS s2l_total_delay_sec_last7_total,\n"
                    + "          SUM(s2l_25ms_delay_sec_last7) AS s2l_25ms_delay_sec_last7_total,\n"
                    + "          SUM(s2l_75ms_delay_sec_last7) AS s2l_75ms_delay_sec_last7_total,\n"
                    + "          SUM(p2s_lost_Leq5_last1) AS p2s_lost_Leq5_last1_total,\n"
                    + "          SUM(p2s_lost_all_last1) AS p2s_lost_all_last1_total,\n"
                    + "          SUM(p2s_lost_Leq5_last7) AS p2s_lost_Leq5_last7_total,\n"
                    + "          SUM(p2s_lost_all_last7) AS p2s_lost_all_last7_total,\n"
                    + "          SUM(crash_cnt_last1) AS crash_cnt_last1_total,\n"
                    + "          SUM(service_cnt_last1) AS service_cnt_last1_total,\n"
                    + "          SUM(crash_cnt_last7) AS crash_cnt_last7_total,\n"
                    + "          SUM(service_cnt_last7) AS service_cnt_last7_total,\n"
                    + "          SUM(s2l_lost_Leq5) AS s2l_lost_Leq5_total,\n"
                    + "          SUM(s2l_lost_all) AS s2l_lost_all_total,\n"
                    + "          SUM(s2l_lost_Leq5_last1) AS s2l_lost_Leq5_last1_total,\n"
                    + "          SUM(s2l_lost_all_last1) AS s2l_lost_all_last1_total,\n"
                    + "          SUM(s2l_lost_Leq5_last7) AS s2l_lost_Leq5_last7_total,\n"
                    + "          SUM(s2l_lost_all_last7) AS s2l_lost_all_last7_total\n"
                    + "        FROM report_datahub.pub_levels_quality_di_1\n"
                    + "        WHERE date_parse(cast( date as VARCHAR), '%Y%m%d') >= DATE('2021-11-21') AND date_parse(cast( date as VARCHAR), '%Y%m%d') <= DATE('2021-11-21') AND CAST(tag AS VARCHAR) = 'Product'\n"
                    + "        GROUP BY date,\n"
                    + "          dim) AS t2 ON t1.date = t2.date AND t1.dim = t2.dim\n"
                    + "    WHERE date_parse(cast( t1.date as VARCHAR), '%Y%m%d') >= DATE('2021-11-21') AND date_parse(cast( t1.date as VARCHAR), '%Y%m%d') <= DATE('2021-11-21') AND CAST(tag AS VARCHAR) = 'Product') AS \"自定义 SQL 查询\"\n"
                    + "  CROSS JOIN (SELECT MAX(date_parse(cast( \"自定义 SQL 查询\".\"date\" as VARCHAR), '%Y%m%d')) AS \"__measure__0\"\n"
                    + "    FROM (SELECT t1.date,\n"
                    + "            CASE WHEN CAST(stat_period AS VARCHAR) = 'day' THEN substr(CAST(date_parse(cast( t1.date as VARCHAR), '%Y%m%d') AS VARCHAR), 1, 10) ELSE concat(CAST(substr(CAST(start_date AS VARCHAR), 1, 10) AS VARCHAR), '~', CAST(substr(CAST(end_date AS VARCHAR), 1, 10) AS VARCHAR)) END AS period,\n"
                    + "          start_date,\n"
                    + "          end_date,\n"
                    + "          stat_period,\n"
                    + "          tag,\n"
                    + "          t1.dim,\n"
                    + "          level1,\n"
                    + "          level2,\n"
                    + "          level3,\n"
                    + "          level4,\n"
                    + "          os,\n"
                    + "          ver,\n"
                    + "          ver_type,\n"
                    + "          domain,\n"
                    + "          country,\n"
                    + "          region,\n"
                    + "          net,\n"
                    + "          vid,\n"
                    + "          project,\n"
                    + "          company_id,\n"
                    + "          company_name,\n"
                    + "          rowsnum,\n"
                    + "          lastusage,\n"
                    + "          thisusage,\n"
                    + "          fiveSecJoinSuccess,\n"
                    + "          totalJoin,\n"
                    + "          cnt_sid,\n"
                    + "          video_freeze_time,\n"
                    + "          video_totaltime,\n"
                    + "          audio_freeze_time,\n"
                    + "          audio_totaltime,\n"
                    + "          s2l_total_delay_sec,\n"
                    + "          s2l_25ms_delay_sec,\n"
                    + "          s2l_75ms_delay_sec,\n"
                    + "          p2s_lost_Leq5,\n"
                    + "          p2s_lost_all,\n"
                    + "          crash_cnt,\n"
                    + "          service_cnt,\n"
                    + "          \"1s_succ_join_ap_cnt\",\n"
                    + "          \"5s_succ_join_ap_cnt\",\n"
                    + "          total_join_ap_cnt,\n"
                    + "          totalJoinSuccess,\n"
                    + "          threeSecJoinSuccess,\n"
                    + "          video_freeze_time_200,\n"
                    + "          video_totaltime_200,\n"
                    + "          video_freeze_time_500,\n"
                    + "          video_totaltime_500,\n"
                    + "          \"3s_succ_join_session_cnt_last1\",\n"
                    + "          \"5s_succ_join_session_cnt_last1\",\n"
                    + "          succ_join_session_cnt_last1,\n"
                    + "          total_join_session_cnt_last1,\n"
                    + "          total_session_cnt_last1,\n"
                    + "          \"1s_succ_join_ap_cnt_last1\",\n"
                    + "          \"5s_succ_join_ap_cnt_last1\",\n"
                    + "          total_join_ap_cnt_last1,\n"
                    + "          \"3s_succ_join_session_cnt_last7\",\n"
                    + "          \"5s_succ_join_session_cnt_last7\",\n"
                    + "          succ_join_session_cnt_last7,\n"
                    + "          total_join_session_cnt_last7,\n"
                    + "          total_session_cnt_last7,\n"
                    + "          \"1s_succ_join_ap_cnt_last7\",\n"
                    + "          \"5s_succ_join_ap_cnt_last7\",\n"
                    + "          total_join_ap_cnt_last7,\n"
                    + "          video_freeze_time_last1,\n"
                    + "          video_totaltime_last1,\n"
                    + "          video_freeze_time_500_last1,\n"
                    + "          video_totaltime_500_last1,\n"
                    + "          video_freeze_time_200_last1,\n"
                    + "          video_totaltime_200_last1,\n"
                    + "          video_freeze_time_last7,\n"
                    + "          video_totaltime_last7,\n"
                    + "          video_freeze_time_500_last7,\n"
                    + "          video_totaltime_500_last7,\n"
                    + "          video_freeze_time_200_last7,\n"
                    + "          video_totaltime_200_last7,\n"
                    + "          audio_freeze_time_last1,\n"
                    + "          audio_totaltime_last1,\n"
                    + "          audio_freeze_time_last7,\n"
                    + "          audio_totaltime_last7,\n"
                    + "          s2l_total_delay_sec_last1,\n"
                    + "          s2l_25ms_delay_sec_last1,\n"
                    + "          s2l_75ms_delay_sec_last1,\n"
                    + "          s2l_total_delay_sec_last7,\n"
                    + "          s2l_25ms_delay_sec_last7,\n"
                    + "          s2l_75ms_delay_sec_last7,\n"
                    + "          p2s_lost_Leq5_last1,\n"
                    + "          p2s_lost_all_last1,\n"
                    + "          p2s_lost_Leq5_last7,\n"
                    + "          p2s_lost_all_last7,\n"
                    + "          crash_cnt_last1,\n"
                    + "          service_cnt_last1,\n"
                    + "          crash_cnt_last7,\n"
                    + "          service_cnt_last7,\n"
                    + "          product_level1,\n"
                    + "          product_level2,\n"
                    + "          product_level3,\n"
                    + "          product_level4,\n"
                    + "          s2l_lost_Leq5,\n"
                    + "          s2l_lost_all,\n"
                    + "          s2l_lost_Leq5_last1,\n"
                    + "          s2l_lost_all_last1,\n"
                    + "          s2l_lost_Leq5_last7,\n"
                    + "          s2l_lost_all_last7,\n"
                    + "          fiveSecJoinSuccess_total,\n"
                    + "          totalJoin_total,\n"
                    + "          cnt_sid_total,\n"
                    + "          video_freeze_time_total,\n"
                    + "          video_totaltime_total,\n"
                    + "          audio_freeze_time_total,\n"
                    + "          audio_totaltime_total,\n"
                    + "          s2l_total_delay_sec_total,\n"
                    + "          s2l_25ms_delay_sec_total,\n"
                    + "          s2l_75ms_delay_sec_total,\n"
                    + "          p2s_lost_Leq5_total,\n"
                    + "          p2s_lost_all_total,\n"
                    + "          crash_cnt_total,\n"
                    + "          service_cnt_total,\n"
                    + "          \"1s_succ_join_ap_cnt_total\",\n"
                    + "          \"5s_succ_join_ap_cnt_total\",\n"
                    + "          total_join_ap_cnt_total,\n"
                    + "          totalJoinSuccess_total,\n"
                    + "          threeSecJoinSuccess_total,\n"
                    + "          video_freeze_time_200_total,\n"
                    + "          video_totaltime_200_total,\n"
                    + "          video_freeze_time_500_total,\n"
                    + "          video_totaltime_500_total,\n"
                    + "          \"3s_succ_join_session_cnt_last1_total\",\n"
                    + "          \"5s_succ_join_session_cnt_last1_total\",\n"
                    + "          succ_join_session_cnt_last1_total,\n"
                    + "          total_join_session_cnt_last1_total,\n"
                    + "          total_session_cnt_last1_total,\n"
                    + "          \"1s_succ_join_ap_cnt_last1_total\",\n"
                    + "          \"5s_succ_join_ap_cnt_last1_total\",\n"
                    + "          total_join_ap_cnt_last1_total,\n"
                    + "          \"3s_succ_join_session_cnt_last7_total\",\n"
                    + "          \"5s_succ_join_session_cnt_last7_total\",\n"
                    + "          succ_join_session_cnt_last7_total,\n"
                    + "          total_join_session_cnt_last7_total,\n"
                    + "          total_session_cnt_last7_total,\n"
                    + "          \"1s_succ_join_ap_cnt_last7_total\",\n"
                    + "          \"5s_succ_join_ap_cnt_last7_total\",\n"
                    + "          total_join_ap_cnt_last7_total,\n"
                    + "          video_freeze_time_last1_total,\n"
                    + "          video_totaltime_last1_total,\n"
                    + "          video_freeze_time_500_last1_total,\n"
                    + "          video_totaltime_500_last1_total,\n"
                    + "          video_freeze_time_200_last1_total,\n"
                    + "          video_totaltime_200_last1_total,\n"
                    + "          video_freeze_time_last7_total,\n"
                    + "          video_totaltime_last7_total,\n"
                    + "          video_freeze_time_500_last7_total,\n"
                    + "          video_totaltime_500_last7_total,\n"
                    + "          video_freeze_time_200_last7_total,\n"
                    + "          video_totaltime_200_last7_total,\n"
                    + "          audio_freeze_time_last1_total,\n"
                    + "          audio_totaltime_last1_total,\n"
                    + "          audio_freeze_time_last7_total,\n"
                    + "          audio_totaltime_last7_total,\n"
                    + "          s2l_total_delay_sec_last1_total,\n"
                    + "          s2l_25ms_delay_sec_last1_total,\n"
                    + "          s2l_75ms_delay_sec_last1_total,\n"
                    + "          s2l_total_delay_sec_last7_total,\n"
                    + "          s2l_25ms_delay_sec_last7_total,\n"
                    + "          s2l_75ms_delay_sec_last7_total,\n"
                    + "          p2s_lost_Leq5_last1_total,\n"
                    + "          p2s_lost_all_last1_total,\n"
                    + "          p2s_lost_Leq5_last7_total,\n"
                    + "          p2s_lost_all_last7_total,\n"
                    + "          crash_cnt_last1_total,\n"
                    + "          service_cnt_last1_total,\n"
                    + "          crash_cnt_last7_total,\n"
                    + "          service_cnt_last7_total,\n"
                    + "          s2l_lost_Leq5_total,\n"
                    + "          s2l_lost_all_total,\n"
                    + "          s2l_lost_Leq5_last1_total,\n"
                    + "          s2l_lost_all_last1_total,\n"
                    + "          s2l_lost_Leq5_last7_total,\n"
                    + "          s2l_lost_all_last7_total\n"
                    + "        FROM report_datahub.pub_levels_quality_di_1 AS t1\n"
                    + "          LEFT JOIN (SELECT date,\n"
                    + "              dim,\n"
                    + "              SUM(fiveSecJoinSuccess) AS fiveSecJoinSuccess_total,\n"
                    + "              SUM(totalJoin) AS totalJoin_total,\n"
                    + "              SUM(cnt_sid) AS cnt_sid_total,\n"
                    + "              SUM(video_freeze_time) AS video_freeze_time_total,\n"
                    + "              SUM(video_totaltime) AS video_totaltime_total,\n"
                    + "              SUM(audio_freeze_time) AS audio_freeze_time_total,\n"
                    + "              SUM(audio_totaltime) AS audio_totaltime_total,\n"
                    + "              SUM(s2l_total_delay_sec) AS s2l_total_delay_sec_total,\n"
                    + "              SUM(s2l_25ms_delay_sec) AS s2l_25ms_delay_sec_total,\n"
                    + "              SUM(s2l_75ms_delay_sec) AS s2l_75ms_delay_sec_total,\n"
                    + "              SUM(p2s_lost_Leq5) AS p2s_lost_Leq5_total,\n"
                    + "              SUM(p2s_lost_all) AS p2s_lost_all_total,\n"
                    + "              SUM(crash_cnt) AS crash_cnt_total,\n"
                    + "              SUM(service_cnt) AS service_cnt_total,\n"
                    + "              SUM(\"1s_succ_join_ap_cnt\") AS \"1s_succ_join_ap_cnt_total\",\n"
                    + "              SUM(\"5s_succ_join_ap_cnt\") AS \"5s_succ_join_ap_cnt_total\",\n"
                    + "              SUM(total_join_ap_cnt) AS total_join_ap_cnt_total,\n"
                    + "              SUM(totalJoinSuccess) AS totalJoinSuccess_total,\n"
                    + "              SUM(threeSecJoinSuccess) AS threeSecJoinSuccess_total,\n"
                    + "              SUM(video_freeze_time_200) AS video_freeze_time_200_total,\n"
                    + "              SUM(video_totaltime_200) AS video_totaltime_200_total,\n"
                    + "              SUM(video_freeze_time_500) AS video_freeze_time_500_total,\n"
                    + "              SUM(video_totaltime_500) AS video_totaltime_500_total,\n"
                    + "              SUM(\"3s_succ_join_session_cnt_last1\") AS \"3s_succ_join_session_cnt_last1_total\",\n"
                    + "              SUM(\"5s_succ_join_session_cnt_last1\") AS \"5s_succ_join_session_cnt_last1_total\",\n"
                    + "              SUM(succ_join_session_cnt_last1) AS succ_join_session_cnt_last1_total,\n"
                    + "              SUM(total_join_session_cnt_last1) AS total_join_session_cnt_last1_total,\n"
                    + "              SUM(total_session_cnt_last1) AS total_session_cnt_last1_total,\n"
                    + "              SUM(\"1s_succ_join_ap_cnt_last1\") AS \"1s_succ_join_ap_cnt_last1_total\",\n"
                    + "              SUM(\"5s_succ_join_ap_cnt_last1\") AS \"5s_succ_join_ap_cnt_last1_total\",\n"
                    + "              SUM(total_join_ap_cnt_last1) AS total_join_ap_cnt_last1_total,\n"
                    + "              SUM(\"3s_succ_join_session_cnt_last7\") AS \"3s_succ_join_session_cnt_last7_total\",\n"
                    + "              SUM(\"5s_succ_join_session_cnt_last7\") AS \"5s_succ_join_session_cnt_last7_total\",\n"
                    + "              SUM(succ_join_session_cnt_last7) AS succ_join_session_cnt_last7_total,\n"
                    + "              SUM(total_join_session_cnt_last7) AS total_join_session_cnt_last7_total,\n"
                    + "              SUM(total_session_cnt_last7) AS total_session_cnt_last7_total,\n"
                    + "              SUM(\"1s_succ_join_ap_cnt_last7\") AS \"1s_succ_join_ap_cnt_last7_total\",\n"
                    + "              SUM(\"5s_succ_join_ap_cnt_last7\") AS \"5s_succ_join_ap_cnt_last7_total\",\n"
                    + "              SUM(total_join_ap_cnt_last7) AS total_join_ap_cnt_last7_total,\n"
                    + "              SUM(video_freeze_time_last1) AS video_freeze_time_last1_total,\n"
                    + "              SUM(video_totaltime_last1) AS video_totaltime_last1_total,\n"
                    + "              SUM(video_freeze_time_500_last1) AS video_freeze_time_500_last1_total,\n"
                    + "              SUM(video_totaltime_500_last1) AS video_totaltime_500_last1_total,\n"
                    + "              SUM(video_freeze_time_200_last1) AS video_freeze_time_200_last1_total,\n"
                    + "              SUM(video_totaltime_200_last1) AS video_totaltime_200_last1_total,\n"
                    + "              SUM(video_freeze_time_last7) AS video_freeze_time_last7_total,\n"
                    + "              SUM(video_totaltime_last7) AS video_totaltime_last7_total,\n"
                    + "              SUM(video_freeze_time_500_last7) AS video_freeze_time_500_last7_total,\n"
                    + "              SUM(video_totaltime_500_last7) AS video_totaltime_500_last7_total,\n"
                    + "              SUM(video_freeze_time_200_last7) AS video_freeze_time_200_last7_total,\n"
                    + "              SUM(video_totaltime_200_last7) AS video_totaltime_200_last7_total,\n"
                    + "              SUM(audio_freeze_time_last1) AS audio_freeze_time_last1_total,\n"
                    + "              SUM(audio_totaltime_last1) AS audio_totaltime_last1_total,\n"
                    + "              SUM(audio_freeze_time_last7) AS audio_freeze_time_last7_total,\n"
                    + "              SUM(audio_totaltime_last7) AS audio_totaltime_last7_total,\n"
                    + "              SUM(s2l_total_delay_sec_last1) AS s2l_total_delay_sec_last1_total,\n"
                    + "              SUM(s2l_25ms_delay_sec_last1) AS s2l_25ms_delay_sec_last1_total,\n"
                    + "              SUM(s2l_75ms_delay_sec_last1) AS s2l_75ms_delay_sec_last1_total,\n"
                    + "              SUM(s2l_total_delay_sec_last7) AS s2l_total_delay_sec_last7_total,\n"
                    + "              SUM(s2l_25ms_delay_sec_last7) AS s2l_25ms_delay_sec_last7_total,\n"
                    + "              SUM(s2l_75ms_delay_sec_last7) AS s2l_75ms_delay_sec_last7_total,\n"
                    + "              SUM(p2s_lost_Leq5_last1) AS p2s_lost_Leq5_last1_total,\n"
                    + "              SUM(p2s_lost_all_last1) AS p2s_lost_all_last1_total,\n"
                    + "              SUM(p2s_lost_Leq5_last7) AS p2s_lost_Leq5_last7_total,\n"
                    + "              SUM(p2s_lost_all_last7) AS p2s_lost_all_last7_total,\n"
                    + "              SUM(crash_cnt_last1) AS crash_cnt_last1_total,\n"
                    + "              SUM(service_cnt_last1) AS service_cnt_last1_total,\n"
                    + "              SUM(crash_cnt_last7) AS crash_cnt_last7_total,\n"
                    + "              SUM(service_cnt_last7) AS service_cnt_last7_total,\n"
                    + "              SUM(s2l_lost_Leq5) AS s2l_lost_Leq5_total,\n"
                    + "              SUM(s2l_lost_all) AS s2l_lost_all_total,\n"
                    + "              SUM(s2l_lost_Leq5_last1) AS s2l_lost_Leq5_last1_total,\n"
                    + "              SUM(s2l_lost_all_last1) AS s2l_lost_all_last1_total,\n"
                    + "              SUM(s2l_lost_Leq5_last7) AS s2l_lost_Leq5_last7_total,\n"
                    + "              SUM(s2l_lost_all_last7) AS s2l_lost_all_last7_total\n"
                    + "            FROM report_datahub.pub_levels_quality_di_1\n"
                    + "            WHERE date_parse(cast( date as VARCHAR), '%Y%m%d') >= DATE('2021-11-21') AND date_parse(cast( date as VARCHAR), '%Y%m%d') <= DATE('2021-11-21') AND CAST(tag AS VARCHAR) = 'Product'\n"
                    + "            GROUP BY date,\n"
                    + "              dim) AS t2 ON t1.date = t2.date AND t1.dim = t2.dim\n"
                    + "        WHERE date_parse(cast( t1.date as VARCHAR), '%Y%m%d') >= DATE('2021-11-21') AND date_parse(cast( t1.date as VARCHAR), '%Y%m%d') <= DATE('2021-11-21') AND CAST(tag AS VARCHAR) = 'Product') AS \"自定义 SQL 查询\"\n"
                    + "    HAVING COUNT(1) > 0) AS \"t0\"\n"
                    + "WHERE CASE WHEN CAST(\"自定义 SQL 查询\".\"tag\" AS VARCHAR) = 'Industry' AND CAST(\"自定义 SQL 查询\".\"product_level1\" AS VARCHAR) = 'RTC' AND CAST(\"自定义 SQL 查询\".\"dim\" AS VARCHAR) = 'osver' THEN 0 WHEN CAST(\"自定义 SQL 查询\".\"tag\" AS VARCHAR) = 'VerType' AND CAST(\"自定义 SQL 查询\".\"product_level1\" AS VARCHAR) = 'RTC' AND CAST(\"自定义 SQL 查询\".\"dim\" AS VARCHAR) = 'osver' THEN 0 WHEN CAST(\"自定义 SQL 查询\".\"tag\" AS VARCHAR) = 'Product' AND CAST(\"自定义 SQL 查询\".\"dim\" AS VARCHAR) = 'osver' AND CAST(\"自定义 SQL 查询\".\"product_level1\" AS VARCHAR) = 'RTC' THEN 1 ELSE 0 END AND CAST(\"自定义 SQL 查询\".\"level2\" AS VARCHAR) = 'Native' AND DATE_ADD('SECOND', 0, date_parse(cast( \"自定义 SQL 查询\".\"date\" as VARCHAR), '%Y%m%d')) = DATE_ADD('SECOND', 0, \"t0\".\"__measure__0\")\n"
                    + "HAVING COUNT(1) > 0";
}
